//
//  GBDocSetOutputGenerator.m
//  appledoc
//
//  Created by Tomaz Kragelj on 29.11.10.
//  Copyright 2010 Gentle Bytes. All rights reserved.
//

#import "GBDocSetOutputGenerator.h"

@interface GBDocSetOutputGenerator ()

- (BOOL)moveSourceFilesToDocuments:(NSError **)error;

@end

#pragma mark -

@implementation GBDocSetOutputGenerator

#pragma Generation handling

- (BOOL)generateOutputWithStore:(id<GBStoreProviding>)store error:(NSError **)error {
	NSParameterAssert(self.previousGenerator != nil);
	if (![super generateOutputWithStore:store error:error]) return NO;
	if (![self moveSourceFilesToDocuments:error]) return NO;
	return YES;
}

- (BOOL)moveSourceFilesToDocuments:(NSError **)error {
	// Prepare all paths. Note that we determine the exact subdirectory by searching for documents-template and using it's subdirectory as the guide.
	NSString *sourceFilesPath = [self.previousGenerator.outputUserPath stringByStandardizingPath];
	NSString *documentsPath = nil;
	for (NSString *template in [self.templateFiles allKeys]) {
		if ([template hasSuffix:@"documents-template"]) {
			documentsPath = [template stringByDeletingLastPathComponent];
			break;
		}
	}
	
	// If documents template wasn't found, exit.
	if (!documentsPath) {
		if (error) {
			NSDictionary *info = [NSDictionary dictionaryWithObjectsAndKeys:
								  @"Documents template is missing!", NSLocalizedDescriptionKey, 
								  @"documents-template file is required to determine location for Documents path in DocSet bundle!", NSLocalizedFailureReasonErrorKey, nil];
			*error = [NSError errorWithDomain:@"appledoc" code:1 userInfo:info];
		}
		GBLogWarn(@"Failed finding documents-template in '%@'!", self.templateUserPath);
		return NO;
	}
	
	// First step is to move all files generated by previous generator as the Documents subfolder of docset structure.
	NSString *destPath = [self.outputUserPath stringByAppendingPathComponent:documentsPath];
	NSString *movePath = [destPath stringByAppendingPathComponent:@"Documents"];
	if (![self.fileManager moveItemAtPath:sourceFilesPath toPath:[movePath stringByStandardizingPath] error:error]) {
		GBLogWarn(@"Failed moving files from '%@' to '%@'!", self.previousGenerator.outputUserPath, movePath);
		return NO;
	}
}

#pragma mark Overriden methods

- (NSString *)outputSubpath {
	return @"docset";
}

@end
